apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: create-customer-details-rest
  namespace: vadym
  annotations:
    ab-image-name: "ab-is-image"
    ab-bars:
      - bar-name: bar-1
        projects:
          - createcustomer
          - createcustomerJava
spec:
  designerFlowsOperationMode: disabled
  license:
    accept: true
    license: L-UTKS-P46KK2
    use: AppConnectEnterpriseNonProductionFREE
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  useCommonServices: true
  version: 12.0.10.0-r1-lts
  adminServerSecure: true
  pod:
    containers:
      runtime:
        image: image-registry.openshift-image-registry.svc:5000/ci/create-customer-details-rest:726b8ce435b1fe216a7a9581cc701d407e91e4cd
        imagePullPolicy: Always
  configurations:
    - create-customer-serverconf.yaml
    - create-customer-policy
